// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_yj0WzWbnxBU4gnyrmya1nYe0bMEZX8',
    appId: '1:382330631143:web:db845662778eefc2294342',
    messagingSenderId: '382330631143',
    projectId: 'clone-bdda8',
    authDomain: 'clone-bdda8.firebaseapp.com',
    storageBucket: 'clone-bdda8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEJfVY3W2oxfBS47aWzBV2NkW1VKY6TS8',
    appId: '1:382330631143:android:bc9fa724fd55260d294342',
    messagingSenderId: '382330631143',
    projectId: 'clone-bdda8',
    storageBucket: 'clone-bdda8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCodlqsLUjymubbYY6uE-HOrCkn_vaPxXk',
    appId: '1:382330631143:ios:bc56bfab0300e7e3294342',
    messagingSenderId: '382330631143',
    projectId: 'clone-bdda8',
    storageBucket: 'clone-bdda8.appspot.com',
    iosBundleId: 'com.example.amaznoClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCodlqsLUjymubbYY6uE-HOrCkn_vaPxXk',
    appId: '1:382330631143:ios:efdcb7d73c52c3c7294342',
    messagingSenderId: '382330631143',
    projectId: 'clone-bdda8',
    storageBucket: 'clone-bdda8.appspot.com',
    iosBundleId: 'com.example.amaznoClone.RunnerTests',
  );
}
